title: Annie Chen
logo: /assets/photo.jpg
description: I'm Annie Chen, a Data Science graduate from UCLA specializing in data analysis, machine learning, and visualization. Passionate about solving problems through data in sales and manufacturing. Ready to create impactful solutions for your organization.
show_downloads: False
theme: jekyll-theme-minimal
