title: Yi-An Chen 
logo: /assets/img/photo-circle.png
description: ""
show_downloads: false
theme: jekyll-theme-minimal
include:
  - /assets/css/style.css 
include:
  - _pages
collections:
  pages:
    output: true


